EventManager/Models/Attendee.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EventManager.Models
{
    public class Attendee
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AttendeeId {get;set;}

        [Required(ErrorMessage ="Please enter your name")]
        public string AttendeeName { get;set;}

        [Required(ErrorMessage ="Please enter a valid email address")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage ="Email format is invalid.")]
        public string AttendeeEmail { get; set; }

        [Required]
        public int EventId { get;set;}

        [ForeignKey("EventId")]
        public Event Events { get;set;}
    }
}

EventManager/Controllers/AttendeeController.cs
using EventManager.Data;
using EventManager.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EventManager.Controllers
{
    public class AttendeeController : Controller
    {
        private readonly IEventRepository _eventRepository;
        private EntityDbContext _entityDbContext;
        private UserManager<IdentityUser> _userManager;
        public AttendeeController(IEventRepository eventRepository, EntityDbContext entityDbContext, UserManager<IdentityUser> userManager)
        {
            _eventRepository = eventRepository;
            _entityDbContext = entityDbContext;
            _userManager = userManager;
        }
        public IActionResult List()
        {
            var _event = _eventRepository.GetAllAttendees();
            return View(_event);
        }
        public IActionResult Confirmation()
        {
            var attendees = new Event();
            attendees.EventRegistrations++;
            return View();
        }
        [HttpGet]
        public IActionResult AttendeeReg(int EventID)
        {
            //var Event = _eventRepository.GetEventId(eventID);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AttendeeReg(Attendee attendee)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                //var Event = _eventRepository.GetEventId(EventId);
                attendee = new Attendee
                {
                    AttendeeName = user.UserName,
                    AttendeeEmail = user.Email
                };
                _eventRepository.AddAttendee(attendee);

                return RedirectToAction("Confirmation");

            }

            return View(attendee);
        }
    }
}

EventManager/Controllers/EventController.cs
using EventManager.Data;
using Microsoft.AspNetCore.Mvc;

namespace EventManager.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventRepository _eventRepository;
        public EventController(IEventRepository eventRepository)
        {
            _eventRepository = eventRepository;
        }
        public IActionResult Index()
        {
            var _events = _eventRepository.GetAllEvents().OrderBy(s => s.EventStartDate); ;
            return View(_events);
        }
        public IActionResult Details(int id)
        {
            var _event = _eventRepository.GetEventId(id);
            return View(_event);
        }

    }
}

EventManager/Views/Attendee/AttendeeReg.cshtml
@model Attendee
@{
    ViewData["Title"] = "Register";
}
<h2>Event Registration</h2>
<hr />

<p>
    <span class="fw-bold">
        Name
    </span>: @User.Identity.Name
</p>

<p>
    <a asp-action="Confirmation" asp-controller="Attendee" asp-route-id="@Model.EventId" asp-route-id="@Model.AttendeeId" class="btn btn-primary">Complete Registration</a>
    @* <input asp-action="Confirmation" asp-controller="Attendee" value="Complete Registration" class="btn btn-primary" @* asp-route-id="@Model.AttendeeId" /> *@
    <a asp-action="Details" asp-controller="Event" asp-route-id="@Model.EventId" class="btn btn-outline-primary">Back to Event Details</a>
</p>

EventManager/Views/Attendee/Confirmation.cshtml
@model Attendee
@{
    ViewData["Title"] = "Confirmation";
}
<h1>Thank You for Registering!</h1>
<hr />

<partial name="_EventDetails" model="@Model" />

<p>
    <strong>List of attendees:</strong>
    <br />
    <div></div> @* Attendee details *@
</p>

<p>
    <button class="btn btn-primary"  type="submit">
        <a class="btn btn-primary" 
        asp-action="Index" asp-controller="Event">Return to Home Page</a>
    </button>
</p>

EventManager/Views/Attendee/List.cshtml
@model IEnumerable<Attendee>
@{
    ViewData["Title"] = "List";
}
<h2>List of Attendees</h2>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AttendeeName)
                @* AttendeeNamee *@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AttendeeEmail)
                @* AttendeeEmail *@
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.AttendeeName
                    @* Attendee Name *@
                </td>
                <td>
                    @item.AttendeeEmail
                    @* Attendee Email *@
                </td>
            </tr>
        }
    </tbody>

</table>

<div class="text-danger"><strong>Total Attendees: </strong>@Model.Count()</div> @*EventRegistrations*@